### ISSUE TITLE
it is not working on my case - 

### ISSUE THREAD

**Issue by gnkarn** [yann25/Sonoff-Tasmota_autoflash#14]
this is the error i receive

Please connect your device now
Aviable Ports:
/dev/cu.CRIUS_BT-DevB - n/a
/dev/cu.HC-05Storm-DevB - n/a
/dev/cu.HB-02-DevB - n/a
/dev/cu.Bluetooth-Incoming-Port - n/a
/dev/cu.usbserial-AM01RMWQ - FT232R USB UART - FT232R USB UART
Which port do you want to use?
/dev/cu.usbserial-AM01RMWQ
Which device are you using? Type 0 for touch or 4CH and 1 for the others
1
/var/folders/s5/4rjcd2z95pq6k_lc2cyrynhm0000gp/T/firmware.bin
https://github.com/arendst/Sonoff-Tasmota/releases/download/v5.5.2/sonoff-ds18x20.bin
(' The file should be ', 487840)
(' The file is ', 487840)
Download succsseful
esptool.py v1.1
Connecting...
Erasing flash (this may take a while)...
0
Reconnect then press enter

usage: esptool write_flash [-h] [--flash_freq {40m,26m,20m,80m}]
                           [--flash_mode {qio,qout,dio,dout}]
                           [--flash_size {4m,2m,8m,16m,32m,16m-c1,32m-c1,32m-c2}]
                           [--no-progress] [--verify]
                           <address> <filename> [<address> <filename> ...]
esptool write_flash: error: argument --flash_size/-fs: invalid choice: 'detect' (choose from '4m', '2m', '8m', '16m', '32m', '16m-c1', '32m-c1', '32m-c2')
Error while writing. Check your connection.
iMac-Gus-os10-ext:~ Gus-nuevo$

**Comment by gnkarn** [comment]
i was able to flash it , but now is throwing this error , on terminal continuously

Fatal exception (0): 
epc1=0x4022b378, epc2=0x00000000, epc3=0x00000000, excvaddr=0x00000000, depc=0x00000000

anything else i could try?

**Comment by davidelang** [comment]
On Mon, 14 Aug 2017, gus wrote:

> Which device are you using? Type 0 for touch or 4CH and 1 for the others
> 1

Try saying 0 here, this is the DOUT selection, it used to be 4ch only, but more 
devices require it now, and it works everywhere

**Comment by gnkarn** [comment]
just the  simple type 1, will try with 0 , then

**Comment by gnkarn** [comment]
now , the error is different , 

Aviable Ports:
/dev/cu.CRIUS_BT-DevB - n/a
/dev/cu.HC-05Storm-DevB - n/a
/dev/cu.HB-02-DevB - n/a
/dev/cu.Bluetooth-Incoming-Port - n/a
/dev/cu.usbserial-AM01RMWQ - FT232R USB UART - FT232R USB UART
Which port do you want to use?
/dev/cu.usbserial-AM01RMWQ
Which device are you using? Type 0 for touch or 4CH and 1 for the others
0
/var/folders/s5/4rjcd2z95pq6k_lc2cyrynhm0000gp/T/firmware.bin
https://github.com/arendst/Sonoff-Tasmota/releases/download/v5.5.2/sonoff-ds18x20.bin
(' The file should be ', 487840)
(' The file is ', 487840)
Download succsseful
esptool.py v2.0.1
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/bin/esptool.py", line 2412, in <module>
    _main()
  File "/Library/Frameworks/Python.framework/Versions/2.7/bin/esptool.py", line 2405, in _main
    main()
  File "/Library/Frameworks/Python.framework/Versions/2.7/bin/esptool.py", line 2128, in main
    esp = ESPLoader.detect_chip(args.port, initial_baud, args.before)
  File "/Library/Frameworks/Python.framework/Versions/2.7/bin/esptool.py", line 201, in detect_chip
    detect_port = ESPLoader(port, baud)
  File "/Library/Frameworks/Python.framework/Versions/2.7/bin/esptool.py", line 175, in __init__
    self._port = serial.serial_for_url(port)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/serial/__init__.py", line 88, in serial_for_url
    instance.open()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/serial/serialposix.py", line 268, in open
    raise SerialException(msg.errno, "could not open port {}: {}".format(self._port, msg))
serial.serialutil.SerialException: [Errno 16] could not open port /dev/cu.usbserial-AM01RMWQ: [Errno 16] Resource busy: '/dev/cu.usbserial-AM01RMWQ'
256

**Comment by gnkarn** [comment]
i had terminal opened , will try again..

**Comment by gnkarn** [comment]
now ended , ok 
like with 1 

esptool.py v2.0.1
Connecting....
Detecting chip type... ESP8266
Chip is ESP8266
Uploading stub...
Running stub...
Stub running...
Configuring flash size...
Auto-detected Flash size: 1MB
Compressed 487840 bytes to 334087...
Wrote 487840 bytes (334087 compressed) at 0x00000000 in 29.6 seconds (effective 131.9 kbit/s)...
Hash of data verified.

Leaving...
Hard resetting...
Successful

but , then , is showing the same error on terminal .

**Comment by gnkarn** [comment]
Fatal exception (0): 
epc1=0x4022b378, epc2=0x00000000, epc3=0x00000000, excvaddr=0x00000000, depc=0x00000000

**Comment by gnkarn** [comment]
i also tested by uploading the blink code , and the behavior is exactly the same , 
so i guess there is something else with the module going on .

by the way it worked fine , with the original factory firmware , before flashing .

is there a way i could  erase it in a "safe way" so to be sure there is no garbage in memory , or a corrupted memory layout?

**Comment by davidelang** [comment]
create a file that's all zeros (dd if=/dev/zero of=filename bs=1024k count=1024) 
and flash that file. nothing will happen with that file, but it will make sure 
there isn't any leftover stuff to confuse tasmota.

**Comment by gnkarn** [comment]
ok,should i flash it starting at address 0?

**Comment by davidelang** [comment]
yes

**Comment by gnkarn** [comment]
ok, i zeroed it , and confirm , that the message with the blank chip is correct :
 ets Jan  8 2013,rst cause:1, boot mode:(3,6)

ets_main.c 

then  loaded the blink sketch , with 1 M 64k spiff , xtall 26Mhz ,flash  40 mhz, cpu 80mhz

and ..

the same error  shown on terminal ,  it seams it is self reseting 

i haven't tested it , disconnecting the programing header , im wondering if this could interfere on the reset logic ??

**Comment by gnkarn** [comment]
Fatal exception (0): 
epc1=0x40207508, epc2=0x00000000, epc3=0x00000000, excvaddr=0x00000000, depc=0x00000000
